#!/bin/bash
FOO=${CACHE_TAG:=latest}
BAR=${SOURCE_BRANCH:=`git rev-parse --abbrev-ref HEAD`}
BAZ=${IMAGE_NAME:=`whoami`/`git config --local remote.origin.url|sed -n 's#.*/\([^.]*\)\.git#\1#p'`:git-local}
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VCS_URL=`git config --get remote.origin.url` \
             --build-arg SOURCE_VERSION=$SOURCE_BRANCH \
             --build-arg VERSION=$CACHE_TAG -t $IMAGE_NAME .
